/* "use client";
import { NavBar } from "@/components/NavBar";
import "./globals.css";
import { Inter } from "next/font/google";
import Footer from "@/components/Footer";
import WhatsAppBtn from "@/components/WhatsAppBtn";
import Copyright from "@/components/Copyright";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata{
//   title: "Martens todo en aberturas",
//   description: "Generated by create next app",

// }

// export async function generateMetadata({ params }) {
//   return {  title: "Martens todo en aberturas",
//   description: "Generated by create next app",
// };
// }

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <body className={inter.className}>
        <NavBar />
        {children}
        <WhatsAppBtn />
        <footer>
          <Footer />
          <Copyright />
        </footer>
      </body>
    </html>
  );
}
 */

import "./globals.css";
import { Inter } from "next/font/google";
import { NavBar } from "@/components/NavBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Martens Aberturas",
  description: "Martens Aberturas: Fabricamos aberturas de alta calidad desde 1957. Con un enfoque en la excelencia y la satisfacción del cliente, ofrecemos modelos únicos y duraderos. Descubre nuestra historia de adaptación, calidad y relaciones sólidas con clientes satisfechos. ¡Confía en nosotros para satisfacer tus necesidades actuales y futuras en aberturas de calidad",
  keywords:"Martens Aberturas, Aberturas de calidad, Trabajos en hierro, Aberturas de alta calidad, Fábrica de aberturas, Modelos únicos de aberturas, puertas, portones, escaleras , pergolas , tandil , soluciones generales Tandil",
  author:"Lis Medina y Santiago Pereira",
  // icons: {
  //   icon: DoorBackIcon,
  // },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <>
          <NavBar />
          {children}
        </>
      </body>
    </html>
  );
}
