let products = [
  {
    name: "Puerta de ingreso",
    description: "Puerta de ingreso fabricada en aluminio de 4 hojas",
    category: "puertas",
    id: 0,
    image: "./images/PUERTAS/chicas/1.jpeg",
    imageModal: "./images/PUERTAS/1.jpeg",
  },
  {
    name: "Puerta de cocina medio vidrio",
    description: "Puerta cocina medio vidrio fabricada en aluminio blanco",
    category: "puertas",
    id: 1,
    image: "./images/PUERTAS/chicas/2.jpeg",
    imageModal: "./images/PUERTAS/2.jpeg",
  },
  {
    name: "Puerta de 2 hojas",
    description: "Puerta de 2 hojas fabricada en aluminio con melamina",
    category: "puertas",
    id: 2,
    image: "./images/PUERTAS/chicas/3.jpeg",
    imageModal: "./images/PUERTAS/3.jpeg",
  },
  {
    name: "Puerta salida de emergencias",
    description:
      "Salida de emergencia con cierre antipánico fabricada en aluminio",
    category: "puertas",
    id: 3,
    image: "./images/PUERTAS/chicas/4.jpeg",
    imageModal: "./images/PUERTAS/4.jpeg",
  },
  {
    name: "Puerta ciega",
    description: "Puerta ciega fabricada en aluminio anodizado",
    category: "puertas",
    id: 4,
    image: "./images/PUERTAS/chicas/5.jpeg",
    imageModal: "./images/PUERTAS/5.jpeg",
  },
  {
    name: "Cerramiento para iglesia",
    description: "Cerramiento para iglesia en aluminio con DVH",
    category: "puertas",
    id: 5,
    image: "./images/PUERTAS/chicas/6.jpeg",
    imageModal: "./images/PUERTAS/6.jpeg",
  },
  {
    name: "Aberturas irregulares",
    description: "Aberturas irregulares fabricadas en aluminio blanco y DVH",
    category: "puertas",
    id: 6,
    image: "./images/PUERTAS/chicas/7.jpeg",
    imageModal: "./images/PUERTAS/7.jpeg",
  },
  {
    name: "Puerta de aluminio",
    description: "Puerta fabricada en aluminio de 2 hojas",
    category: "puertas",
    id: 7,
    image: "./images/PUERTAS/chicas/8.jpeg",
    imageModal: "./images/PUERTAS/8.jpeg",
  },
  {
    name: "Puerta medio vidrio",
    description: "Puerta medio vidrio de color blanco de alta calidad",
    category: "puertas",
    id: 8,
    image: "./images/PUERTAS/chicas/9.jpeg",
    imageModal: "./images/PUERTAS/9.jpeg",
  },
  {
    name: "Portón corredizo recto",
    description: "producto de alta calidad",
    category: "Portón corredizo recto de 2 hojas para frente",
    id: 12,
    image: "./images/porton/chicas/1.jpeg",
    imageModal: "./images/porton/1.jpeg",
  },
  {
    name: "Portón levadizo",
    description: "Portón levadizo ciego con molduras horizontales",
    category: "portones",
    id: 13,
    image: "./images/porton/chicas/2.jpeg",
    imageModal: "./images/porton/2.jpeg",
  },
  {
    name: "Portón corredizo recto",
    description: "Portón corredizo recto de diseño personalizado",
    category: "portones",
    id: 14,
    image: "./images/porton/chicas/3.jpeg",
    imageModal: "./images/porton/3.jpeg",
  },
  {
    name: "Portón de aluminio",
    description: "Portón fabricado en aluminio de 3 hojas",
    category: "portones",
    id: 15,
    image: "./images/porton/chicas/4.jpeg",
    imageModal: "./images/porton/4.jpeg",
  },
  {
    name: "Doble portón levadizo",
    description: "Doble portón levadizo fabricado en aluminio",
    category: "portones",
    id: 16,
    image: "./images/porton/chicas/5.jpeg",
    imageModal: "./images/porton/5.jpeg",
  },
  {
    name: "Portón doble hoja",
    description: "Portón doble hoja fabricado en aluminio",
    category: "portones",
    id: 17,
    image: "./images/porton/chicas/6.jpeg",
    imageModal: "./images/porton/6.jpeg",
  },
  {
    name: "Ventana de aluminio",
    description: "Ventana de aluminio blanco y negro modena",
    category: "ventanas",
    id: 18,
    image: "./images/VENTANA/chicas/1.jpeg",
    imageModal: "./images/VENTANA/1.jpeg",
  },
  {
    name: "Trabajos en ciudad y campo",
    description: "Hacemos trabajos en ciudad y campo",
    category: "ventanas",
    id: 19,
    image: "./images/VENTANA/chicas/2.jpeg",
    imageModal: "./images/VENTANA/2.jpeg",
  },
  {
    name: "Ventana de aluminio",
    description: "Ventana de aluminio corredizo con bipunto",
    category: "ventanas",
    id: 20,
    image: "./images/VENTANA/chicas/3.jpeg",
    imageModal: "./images/VENTANA/3.jpeg",
  },
  {
    name: "Ventana de aluminio",
    description: "Ventana de aluminio corrediza modena",
    category: "ventanas",
    id: 21,
    image: "./images/VENTANA/chicas/4.jpeg",
    imageModal: "./images/VENTANA/4.jpeg",
  },
  {
    name: "Ventana para edificios",
    description: "Ventana modena para edificios a pedido",
    category: "ventanas",
    id: 22,
    image: "./images/VENTANA/chicas/5.jpeg",
    imageModal: "./images/VENTANA/5.jpeg",
  },
  {
    name: "Puerta con DVH",
    description: "Puerta con DVH (obra modena negro)",
    category: "ventanas",
    id: 23,
    image: "./images/VENTANA/chicas/6.jpeg",
    imageModal: "./images/VENTANA/6.jpeg",
  },
  {
    name: "Ventana corrediza",
    description: "Ventana corrediza modena DVH",
    category: "ventanas",
    id: 24,
    image: "./images/VENTANA/chicas/7.jpeg",
    imageModal: "./images/VENTANA/7.jpeg",
  },
  {
    name: "Ventana de Paño fijo",
    description: "Ventana de Paño fijo + hoja de abrir",
    category: "ventanas",
    id: 25,
    image: "./images/VENTANA/chicas/8.jpeg",
    imageModal: "./images/VENTANA/8.jpeg",
  },
  {
    name: "Obra modena blanco",
    description: "Obra modena blanco",
    category: "ventanas",
    id: 26,
    image: "./images/VENTANA/chicas/9.jpeg",
    imageModal: "./images/VENTANA/9.jpeg",
  },
  {
    name: "Puerta tablero inferior chico",
    description: "Puerta tablero inferior chico",
    category: "ventanas",
    id: 27,
    image: "./images/VENTANA/chicas/10.jpeg",
    imageModal: "./images/VENTANA/10.jpeg",
  },
  {
    name: "Cierre bipunto modena blanco",
    description: "Cierre bipunto modena blanco",
    category: "ventanas",
    id: 28,
    image: "./images/VENTANA/chicas/11.jpeg",
    imageModal: "./images/VENTANA/11.jpeg",
  },
  {
    name: "Ventana balcon de 2 hojas",
    description: "Ventana balcón de 2 hojas",
    category: "ventanas",
    id: 29,
    image: "./images/VENTANA/chicas/12.jpeg",
    imageModal: "./images/VENTANA/12.jpeg",
  },

  {
    name: "Escalera de hierro estructural y maderas",
    description: "Escalera de hierro estructural y maderas",
    category: "pergolas",
    id: 30,
    image: "./images/escalerasPergolas/chicas/1.jpeg",
    imageModal: "./images/escalerasPergolas/1.jpeg",
  },
  {
    name: "Escalera de hierro estructural y maderas",
    description: "Escalera de hierro estructural y maderas curva de 90°",
    category: "pergolas",
    id: 31,
    image: "./images/escalerasPergolas/chicas/2.jpeg",
    imageModal: "./images/escalerasPergolas/2.jpeg",
  },
  {
    name: "Escalera de hierro estructural y maderas",
    description:
      "Escalera de hierro estructural y maderas, acceso a primer piso",
    category: "pergolas",
    id: 32,
    image: "./images/escalerasPergolas/chicas/3.jpeg",
    imageModal: "./images/escalerasPergolas/3.jpeg",
  },
  {
    name: "Baranda de escalera",
    description: "Baranda de escalera con adornos en hierro",
    category: "pergolas",
    id: 33,
    image: "./images/escalerasPergolas/chicas/4.jpeg",
    imageModal: "./images/escalerasPergolas/4.jpeg",
  },
  {
    name: "Baranda de escalera",
    description: "Baranda de escalera con adornos en hierro",
    category: "pergolas",
    id: 34,
    image: "./images/escalerasPergolas/chicas/5.jpeg",
    imageModal: "./images/escalerasPergolas/5.jpeg",
  },
  {
    name: "Baranda de escalera",
    description: "Baranda de escalera con adornos en hierro",
    category: "pergolas",
    id: 35,
    image: "./images/escalerasPergolas/chicas/6.jpeg",
    imageModal: "./images/escalerasPergolas/6.jpeg",
  },
  {
    name: "Pérgola a medida",
    description: "Fabricada en caño con techo de madera y cenefas",
    category: "pergolas",
    id: 36,
    image: "./images/escalerasPergolas/chicas/7.jpeg",
    imageModal: "./images/escalerasPergolas/7.jpeg",
  },
  {
    name: "Pérgola a medida",
    description: "Pérgola fabricada a medida a pedido del cliente",
    category: "pergolas",
    id: 37,
    image: "./images/escalerasPergolas/chicas/8.jpeg",
    imageModal: "./images/escalerasPergolas/8.jpeg",
  },
  {
    name: "Pérgola a medida",
    description: "Pérgola fabricada a medida a pedido del cliente",
    category: "pergolas",
    id: 38,
    image: "./images/escalerasPergolas/chicas/9.jpeg",
    imageModal: "./images/escalerasPergolas/9.jpeg",
  },

  {
    name: "Invernadero",
    description: "Invernadero fabricado a medida",
    category: "trabajos",
    id: 39,
    image: "./images/hierro/chicas/a.jpeg",
    imageModal: "./images/hierro/a.jpeg",
  },
  {
    name: "Frente tapa parrilla levadizo",
    description: "Frente tapa parrilla levadizo",
    category: "trabajos",
    id: 40,
    image: "./images/hierro/chicas/b.jpeg",
    imageModal: "./images/hierro/b.jpeg",
  },
  {
    name: "Parasol",
    description: "Parasol",
    category: "trabajos",
    id: 41,
    image: "./images/hierro/chicas/c.jpeg",
    imageModal: "./images/hierro/c.jpeg",
  },
  {
    name: "Spiro chico",
    description: "Spiro chico",
    category: "trabajos",
    id: 42,
    image: "./images/hierro/chicas/d.jpeg",
    imageModal: "./images/hierro/d.jpeg",
  },
  {
    name: "Spiro grande",
    description: "Spiro grande",
    category: "trabajos",
    id: 43,
    image: "./images/hierro/chicas/e.jpeg",
    imageModal: "./images/hierro/e.jpeg",
  },
  {
    name: "Puerta de hierro de 2 hojas",
    description: "Puerta de hierro de 2 hojas",
    category: "trabajos",
    id: 44,
    image: "./images/hierro/chicas/f.jpg",
    imageModal: "./images/hierro/f.jpg",
  },
  {
    name: "Mampara de baño fija",
    description: "Mampara de baño fija",
    category: "soluciones-generales",
    id: 45,
    image: "./images/solucGrales/chicas/1.jpeg",
    imageModal: "./images/solucGrales/1.jpeg",
  },
  {
    name: "Mampara de baño con puerta",
    description: "Mampara de baño con puerta",
    category: "soluciones-generales",
    id: 46,
    image: "./images/solucGrales/chicas/2.jpeg",
    imageModal: "./images/solucGrales/2.jpeg",
  },
  {
    name: "Divisiones interiores",
    description: "Divisiones con aluminio",
    category: "soluciones-generales",
    id: 47,
    image: "./images/solucGrales/chicas/3.jpeg",
    imageModal: "./images/solucGrales/3.jpeg",
  },
  {
    name: "Barandas para piscinas",
    description:
      "Barandas para piscinas fabricadas en hierro y vidrio laminado",
    category: "soluciones-generales",
    id: 48,
    image: "./images/solucGrales/chicas/4.jpeg",
    imageModal: "./images/solucGrales/4.jpeg",
  },
  {
    name: "Barandas para piscinas",
    description:
      "Barandas para piscinas fabricadas en hierro y vidrio laminado",
    category: "soluciones-generales",
    id: 49,
    image: "./images/solucGrales/chicas/5.jpeg",
    imageModal: "./images/solucGrales/5.jpeg",
  },
  {
    name: "Barandas para piscinas",
    description:
      "Barandas para piscinas fabricadas en hierro y vidrio laminado",
    category: "soluciones-generales",
    id: 50,
    image: "./images/solucGrales/chicas/6.jpeg",
    imageModal: "./images/solucGrales/6.jpeg",
  },
  {
    name: "Guarda agua",
    description: "Guarda agua en entrada de vivienda",
    category: "soluciones-generales",
    id: 51,
    image: "./images/solucGrales/chicas/7.jpeg",
    imageModal: "./images/solucGrales/7.jpeg",
  },
  {
    name: "División en aluminio anodizado",
    description: "División en aluminio anodizado",
    category: "soluciones-generales",
    id: 52,
    image: "./images/solucGrales/chicas/8.jpeg",
    imageModal: "./images/solucGrales/8.jpeg",
  },
  {
    name: "Techo en balcón",
    description: "Techo en balcón transparente a medida",
    category: "soluciones-generales",
    id: 53,
    image: "./images/solucGrales/chicas/9.jpeg",
    imageModal: "./images/solucGrales/9.jpeg",
  },
];
export default products;
