let products = [
  {
    name: "Puerta 1",
    description: "producto de alta calidad",
    category: "puertas",
    id: 0,
    image: "./images/PUERTAS/chicas/1.jpeg",
    imageModal: "./images/PUERTAS/1.jpeg",
  },
  {
    name: "Puerta 2",
    description: "producto de alta calidad",
    category: "puertas",
    id: 1,
    image: "./images/PUERTAS/chicas/2.jpeg",
    imageModal: "./images/PUERTAS/2.jpeg",
  },
  {
    name: "Puerta 3",
    description: "producto de alta calidad",
    category: "puertas",
    id: 2,
    image: "./images/PUERTAS/chicas/3.jpeg",
    imageModal: "./images/PUERTAS/3.jpeg",
  },
  {
    name: "Puerta 4",
    description: "producto de alta calidad",
    category: "puertas",
    id: 3,
    image: "./images/PUERTAS/chicas/4.jpeg",
    imageModal: "./images/PUERTAS/4.jpeg",
  },
  {
    name: "Puert 5",
    description: "producto de alta calidad",
    category: "puertas",
    id: 4,
    image: "./images/PUERTAS/chicas/5.jpeg",
    imageModal: "./images/PUERTAS/5.jpeg",
  },
  {
    name: "Puerta 6",
    description: "producto de alta calidad",
    category: "puertas",
    id: 5,
    image: "./images/PUERTAS/chicas/6.jpeg",
    imageModal: "./images/PUERTAS/6.jpeg",
  },
  {
    name: "Puerta 7",
    description: "producto de alta calidad",
    category: "puertas",
    id: 6,
    image: "./images/PUERTAS/chicas/7.jpeg",
    imageModal: "./images/PUERTAS/7.jpeg",
  },
  {
    name: "Puerta 8",
    description: "producto de alta calidad",
    category: "puertas",
    id: 7,
    image: "./images/PUERTAS/chicas/8.jpeg",
    imageModal: "./images/PUERTAS/8.jpeg",
  },
  {
    name: "Puerta 9",
    description: "producto de alta calidad",
    category: "puertas",
    id: 8,
    image: "./images/PUERTAS/chicas/9.jpeg",
    imageModal: "./images/PUERTAS/9.jpeg",
  },
  {
    name: "Puerta 10",
    description: "producto de alta calidad",
    category: "puertas",
    id: 9,
    image: "./images/PUERTAS/chicas/10.jpeg",
    imageModal: "./images/PUERTAS/10.jpeg",
  },

  {
    name: "porton 1",
    description: "producto de alta calidad",
    category: "portones",
    id: 12,
    image: "./images/porton/chicas/1.jpeg",
    imageModal: "./images/porton/1.jpeg",
  },
  {
    name: "porton 2",
    description: "producto de alta calidad",
    category: "portones",
    id: 13,
    image: "./images/porton/chicas/2.jpeg",
    imageModal: "./images/porton/2.jpeg",
  },
  {
    name: "porton 3",
    description: "producto de alta calidad",
    category: "portones",
    id: 14,
    image: "./images/porton/chicas/3.jpeg",
    imageModal: "./images/porton/3.jpeg",
  },
  {
    name: "porton 4",
    description: "producto de alta calidad",
    category: "portones",
    id: 15,
    image: "./images/porton/chicas/4.jpeg",
    imageModal: "./images/porton/4.jpeg",
  },
  {
    name: "porton 5",
    description: "producto de alta calidad",
    category: "portones",
    id: 16,
    image: "./images/porton/chicas/5.jpeg",
    imageModal: "./images/porton/5.jpeg",
  },
  {
    name: "porton 6",
    description: "producto de alta calidad",
    category: "portones",
    id: 17,
    image: "./images/porton/chicas/6.jpeg",
    imageModal: "./images/porton/6.jpeg",
  },
  {
    name: "ventana 1",
    description: "producto de alta calidad",
    category: "ventanas",
    id: 18,
    image: "./images/VENTANA/chicas/1.jpeg",
    imageModal: "./images/VENTANA/1.jpeg",
  },
  {
    name: "ventana 2",
    description: "producto de alta calidad",
    category: "ventanas",
    id: 19,
    image: "./images/VENTANA/chicas/2.jpeg",
    imageModal: "./images/VENTANA/2.jpeg",
  },
  {
    name: "ventana 3",
    description: "producto de alta calidad",
    category: "ventanas",
    id: 20,
    image: "./images/VENTANA/chicas/3.jpeg",
    imageModal: "./images/VENTANA/3.jpeg",
  },
  {
    name: "ventana 4",
    description: "producto de alta calidad",
    category: "ventanas",
    id: 21,
    image: "./images/VENTANA/chicas/4.jpeg",
    imageModal: "./images/VENTANA/4.jpeg",
  },
  {
    name: "ventana 5",
    description: "producto de alta calidad",
    category: "ventanas",
    id: 22,
    image: "./images/VENTANA/chicas/5.jpeg",
    imageModal: "./images/VENTANA/5.jpeg",
  },
  {
    name: "ventana 6",
    description: "producto de alta calidad",
    category: "ventanas",
    id: 23,
    image: "./images/VENTANA/chicas/6.jpeg",
    imageModal: "./images/VENTANA/6.jpeg",
  },
  {
    name: "ventana 7",
    description: "producto de alta calidad",
    category: "ventanas",
    id: 24,
    image: "./images/VENTANA/chicas/7.jpeg",
    imageModal: "./images/VENTANA/7.jpeg",
  },
  {
    name: "ventana 8",
    description: "producto de alta calidad",
    category: "ventanas",
    id: 25,
    image: "./images/VENTANA/chicas/8.jpeg",
    imageModal: "./images/VENTANA/8.jpeg",
  },
  {
    name: "ventana 9",
    description: "producto de alta calidad",
    category: "ventanas",
    id: 26,
    image: "./images/VENTANA/chicas/9.jpeg",
    imageModal: "./images/VENTANA/9.jpeg",
  },
  {
    name: "ventana 10",
    description: "producto de alta calidad",
    category: "ventanas",
    id: 27,
    image: "./images/VENTANA/chicas/10.jpeg",
    imageModal: "./images/VENTANA/10.jpeg",
  },
  {
    name: "ventana 11",
    description: "producto de alta calidad",
    category: "ventanas",
    id: 28,
    image: "./images/VENTANA/chicas/11.jpeg",
    imageModal: "./images/VENTANA/11.jpeg",
  },
  {
    name: "ventana 12",
    description: "producto de alta calidad",
    category: "ventanas",
    id: 29,
    image: "./images/VENTANA/chicas/12.jpeg",
    imageModal: "./images/VENTANA/12.jpeg",
  },

  {
    name: "Escalera 1",
    description: "producto de alta calidad",
    category: "pergolas",
    id: 30,
    image: "./images/escalerasPergolas/chicas/1.jpeg",
    imageModal: "./images/escalerasPergolas/1.jpeg",
  },
  {
    name: "Escalera 2",
    description: "producto de alta calidad",
    category: "pergolas",
    id: 31,
    image: "./images/escalerasPergolas/chicas/2.jpeg",
    imageModal: "./images/escalerasPergolas/2.jpeg",
  },
  {
    name: "Escalera 3",
    description: "producto de alta calidad",
    category: "pergolas",
    id: 32,
    image: "./images/escalerasPergolas/chicas/3.jpeg",
    imageModal: "./images/escalerasPergolas/3.jpeg",
  },
  {
    name: "Escalera 4",
    description: "producto de alta calidad",
    category: "pergolas",
    id: 33,
    image: "./images/escalerasPergolas/chicas/4.jpeg",
    imageModal: "./images/escalerasPergolas/4.jpeg",
  },
  {
    name: "Escalera 5",
    description: "producto de alta calidad",
    category: "pergolas",
    id: 34,
    image: "./images/escalerasPergolas/chicas/5.jpeg",
    imageModal: "./images/escalerasPergolas/5.jpeg",
  },
  {
    name: "Escalera 6",
    description: "producto de alta calidad",
    category: "pergolas",
    id: 35,
    image: "./images/escalerasPergolas/chicas/6.jpeg",
    imageModal: "./images/escalerasPergolas/6.jpeg",
  },

  {
    name: "Pergola  1",
    description: "producto de alta calidad",
    category: "pergolas",
    id: 36,
    image: "./images/escalerasPergolas/chicas/7.jpeg",
    imageModal: "./images/escalerasPergolas/7.jpeg",
  },
  {
    name: "Pergola  2",
    description: "producto de alta calidad",
    category: "pergolas",
    id: 37,
    image: "./images/escalerasPergolas/chicas/8.jpeg",
    imageModal: "./images/escalerasPergolas/8.jpeg",
  },
  {
    name: "Pergola  3",
    description: "producto de alta calidad",
    category: "pergolas",
    id: 38,
    image: "./images/escalerasPergolas/chicas/9.jpeg",
    imageModal: "./images/escalerasPergolas/9.jpeg",
  },

  {
    name: "hierro 1",
    description: "producto de alta calidad",
    category: "trabajos",
    id: 39,
    image: "./images/hierro/chicas/a.jpeg",
    imageModal: "./images/hierro/a.jpeg",
  },
  {
    name: "hierro 2",
    description: "producto de alta calidad",
    category: "trabajos",
    id: 40,
    image: "./images/hierro/chicas/b.jpeg",
    imageModal: "./images/hierro/b.jpeg",
  },
  {
    name: "hierro 3",
    description: "producto de alta calidad",
    category: "trabajos",
    id: 41,
    image: "./images/hierro/chicas/c.jpeg",
    imageModal: "./images/hierro/c.jpeg",
  },
  {
    name: "hierro 4",
    description: "producto de alta calidad",
    category: "trabajos",
    id: 42,
    image: "./images/hierro/chicas/d.jpeg",
    imageModal: "./images/hierro/d.jpeg",
  },
  {
    name: "hierro 5",
    description: "producto de alta calidad",
    category: "trabajos",
    id: 43,
    image: "./images/hierro/chicas/e.jpeg",
    imageModal: "./images/hierro/e.jpeg",
  },
  {
    name: "hierro 6",
    description: "producto de alta calidad",
    category: "trabajos",
    id: 44,
    image: "./images/hierro/chicas/f.jpg",
    imageModal: "./images/hierro/f.jpg",
  },
  {
    name: "soluciones 1",
    description: "producto de alta calidad",
    category: "soluciones-generales",
    id: 45,
    image: "./images/solucGrales/chicas/1.jpeg",
    imageModal: "./images/solucGrales/1.jpeg",
  },
  {
    name: "soluciones 2",
    description: "producto de alta calidad",
    category: "soluciones-generales",
    id: 46,
    image: "./images/solucGrales/chicas/2.jpeg",
    imageModal: "./images/solucGrales/2.jpeg",
  },
  {
    name: "soluciones 3",
    description: "producto de alta calidad",
    category: "soluciones-generales",
    id: 47,
    image: "./images/solucGrales/chicas/3.jpeg",
    imageModal: "./images/solucGrales/3.jpeg",
  },
  {
    name: "soluciones 4",
    description: "producto de alta calidad",
    category: "soluciones-generales",
    id: 48,
    image: "./images/solucGrales/chicas/4.jpeg",
    imageModal: "./images/solucGrales/4.jpeg",
  },
  {
    name: "soluciones 5",
    description: "producto de alta calidad",
    category: "soluciones-generales",
    id: 49,
    image: "./images/solucGrales/chicas/5.jpeg",
    imageModal: "./images/solucGrales/5.jpeg",
  },
  {
    name: "soluciones 6",
    description: "producto de alta calidad",
    category: "soluciones-generales",
    id: 50,
    image: "./images/solucGrales/chicas/6.jpeg",
    imageModal: "./images/solucGrales/6.jpeg",
  },
  {
    name: "soluciones 7",
    description: "producto de alta calidad",
    category: "soluciones-generales",
    id: 51,
    image: "./images/solucGrales/chicas/7.jpeg",
    imageModal: "./images/solucGrales/7.jpeg",
  },
  {
    name: "soluciones 8",
    description: "producto de alta calidad",
    category: "soluciones-generales",
    id: 52,
    image: "./images/solucGrales/chicas/8.jpeg",
    imageModal: "./images/solucGrales/8.jpeg",
  },
  {
    name: "soluciones 9",
    description: "producto de alta calidad",
    category: "soluciones-generales",
    id: 53,
    image: "./images/solucGrales/chicas/9.jpeg",
    imageModal: "./images/solucGrales/9.jpeg",
  },
];
export default products;